# Generated by Django 5.0.9 on 2026-08-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_links",
                to="races.race",
            ),
        ),
        migrations.AddField(
            model_name="magiclink",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="magic_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organisationmember",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.organisation",
            ),
        ),
        migrations.AddField(
            model_name="organisationmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisation_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organisationmember",
            unique_together={("organisation", "user")},
        ),
    ]
