# Generated by Django 5.0.9 on 2026-08-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_by_organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_profiles",
                to="accounts.organisation",
            ),
        ),
    ]
